###### 01-spring-boot-overviewの設定 ######
# どのエンドポイントを外部からアクセス可能にするか
# Can also expose individual endpoints with a comma-delimited list
management.endpoints.web.exposure.include=*

# 名前またはワイルドカードを除外するためのエンドポイント
management.endpoints.web.exposure.exclude=beans,mapping

# Spring Boot Actuatorの設定プロパティで、アプリケーションの 環境変数（environment variables） の情報を info エンドポイントで公開するかどうか
#management.info.env.enabled=true

# カスタムアプリケーション
# エンドポイント:http://localhost:8080/actuator/info
info.app.encoding=@project.build.sourceEncoding@
info.app.java.source=@java.version@
info.app.java.target=@java.version@

# ヘルスの詳細を表示
management.endpoint.health.show-details=always

# メモリメトリクスが収集されるように設定

# 使用可能な最大メモリ量
# /actuator/metrics/jvm.memory.max

# 現在使用しているメモリ量
# /actuator/metrics/jvm.memory.used

#
# アプリケーションのコンテキストパスをセット
#
# すべてのリクエストには接頭辞 /actuator を付ける必要があります
#
server.servlet.context-path=/

#
# Change Spring Boot embedded server port
#
server.port=8080

# Default HTTP session time out
server.servlet.session.timeout=15m

# デフォルトユーザーとパスワードの設定
spring.security.user.name=myadmin
spring.security.user.password=password

# Logging Levels
# TRACE
# DEBUG
# INFO
# WARN
# ERROR
# FATAL
# OFF
#logging.level.org.springframework=DEBUG
logging.level.org.hibernate=TRACE
logging.level.com.giito=INFO

# Log file name
logging.file.name=logs/application.log

#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springdemo
spring.datasource.password=springdemo