# データベース接続
#spring.datasource.url=jdbc:mysql://localhost:3306/hb-01-one-to-one-uni
#spring.datasource.url=jdbc:mysql://localhost:3306/hb-03-one-to-many
#spring.datasource.url=jdbc:mysql://localhost:3306/hb-04-one-to-many-uni
spring.datasource.url=jdbc:mysql://localhost:3306/hb-05-many-to-many

spring.datasource.username=springdemo
spring.datasource.password=springdemo

# Spring Boot bannerを削除
spring.main.banner-mode=off

# ロギングレベルを減らす。ロギングレベルをwanにセットする。
logging.level.root=warn

# JPA/Hibernateのロギングメッセージを見せる
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace

#
# Simple Spring Security
#
spring.security.user.name=scott
spring.security.user.password=test123